USE [SharedServices]
GO

DROP VIEW [dbo].[UNST_TotalOpen]
GO

CREATE VIEW [dbo].[UNST_TotalOpen]
AS
SELECT COUNT([INVOICE_NUM]) AS CountOfOpenUNSTs,
    FORMAT(COALESCE([PROCESS_DATE], [INSERT_DATE]), 'yyyy-MM-dd') AS UNST_DATE
FROM [dbo].[UNST_ZNST]
WHERE [STATUS] NOT IN('Done')
GROUP BY FORMAT(COALESCE([PROCESS_DATE], [INSERT_DATE]), 'yyyy-MM-dd')
GO